export const basic = {
	"array-bracket-newline"         : ["error", "consistent"],
	"array-bracket-spacing"         : "error",
	"array-element-newline"         : ["error", "consistent"],
	"arrow-parens"                  : ["error", "as-needed"],
	"arrow-spacing"                 : "error",
	"block-spacing"                 : "error",
	"brace-style"                   : ["error", "1tbs", {allowSingleLine: true}],
	"comma-dangle"                  : ["error", "always-multiline"],
	"comma-spacing"                 : "error",
	"comma-style"                   : "error",
	"computed-property-spacing"     : "error",
	"dot-location"                  : "error",
	"eol-last"                      : "error",
	"func-call-spacing"             : "error",
	"function-call-argument-newline": ["error", "consistent"],
	"function-paren-newline"        : ["error", "consistent"],
	"generator-star-spacing"        : ["error", {before: false, after: true}],
	"implicit-arrow-linebreak"      : "error",
	"indent"                        : ["error", "tab", {
		VariableDeclarator      : "first",
		FunctionDeclaration     : {parameters: "first"},
		FunctionExpression      : {parameters: "first"},
		CallExpression          : {arguments: "first"},
		ArrayExpression         : "first",
		ObjectExpression        : "first",
		ImportDeclaration       : "first",
		flatTernaryExpressions  : true,
		offsetTernaryExpressions: true,
	}],
	"jsx-quotes"                 : "error",
	"key-spacing"                : ["error", {align: "colon"}],
	"keyword-spacing"            : "error",
	"line-comment-position"      : "off",
	"linebreak-style"            : "error",
	"lines-around-comment"       : "off",
	"lines-between-class-members": ["error", "never"],
	"max-len"                    : ["error", {code: 120, tabWidth: 2}],
	"max-statements-per-line"    : "error",
	"multiline-ternary"          : ["error", "always-multiline"],
	"new-parens"                 : "error",
	"newline-per-chained-call"   : "off",
	"no-extra-parens"            : "error",
	"no-mixed-spaces-and-tabs"   : ["error", "smart-tabs"],
	"no-multi-spaces"            : ["error", {
		ignoreEOLComments: true,
		exceptions       : {Property: true, VariableDeclarator: true, ImportDeclaration: true},
	}],
	"no-multiple-empty-lines"         : ["error", {max: 1, maxBOF: 0, maxEOF: 1}],
	"no-tabs"                         : ["error", {allowIndentationTabs: true}],
	"no-trailing-spaces"              : "error",
	"no-whitespace-before-property"   : "error",
	"nonblock-statement-body-position": "error",
	"object-curly-newline"            : "error",
	"object-curly-spacing"            : "error",
	"object-property-newline"         : ["error", {allowAllPropertiesOnSameLine: true}],
	"operator-linebreak"              : ["error", "before"],
	"padded-blocks"                   : ["error", "never"],
	"padding-line-between-statements" : [
		"error",
		{blankLine: "always", prev: "*", next: "return"},
		{blankLine: "always", prev: ["const", "let", "var"], next: "*"},
		{blankLine: "any", prev: ["const", "let", "var"], next: ["const", "let", "var"]},
		{blankLine: "always", prev: "directive", next: "*"},
		{blankLine: "any", prev: "directive", next: "directive"},
	],
	"quotes"                     : ["error", "double", {avoidEscape: true, allowTemplateLiterals: true}],
	"rest-spread-spacing"        : "error",
	"semi"                       : ["error", "never", {beforeStatementContinuationChars: "never"}],
	"semi-spacing"               : "error",
	"semi-style"                 : ["error", "first"],
	"space-before-blocks"        : "error",
	"space-before-function-paren": ["error", {
		anonymous : "never",
		named     : "never",
		asyncArrow: "always",
	}],
	"space-in-parens"       : "error",
	"space-infix-ops"       : "error",
	"space-unary-ops"       : ["error", {words: true, nonwords: false}],
	"switch-colon-spacing"  : "error",
	"template-curly-spacing": "error",
	"template-tag-spacing"  : "error",
	"unicode-bom"           : "error",
	"wrap-iife"             : ["error", "inside", {functionPrototypeMethods: true}],
	"wrap-regex"            : "off",
	"yield-star-spacing"    : "error",
}

export const extended = {
	"arrow-body-style"              : "off",
	"capitalized-comments"          : ["error", "always", {ignoreInlineComments: true}],
	"curly"                         : ["error", "multi-or-nest", "consistent"],
	"dot-notation"                  : "error",
	"eqeqeq"                        : "error",
	"logical-assignment-operators"  : ["error", "always", {enforceForIfStatements: true}],
	"multiline-comment-style"       : "error",
	"no-confusing-arrow"            : ["error", {onlyOneSimpleParam: true}],
	"no-div-regex"                  : "off",
	"no-else-return"                : "off",
	"no-extra-bind"                 : "error",
	"no-extra-boolean-cast"         : ["error", {enforceForLogicalOperands: true}],
	"no-extra-label"                : "error",
	"no-floating-decimal"           : "error",
	"no-implicit-coercion"          : ["error", {boolean: false}],
	"no-lonely-if"                  : "error",
	"no-undef-init"                 : "error",
	"no-unneeded-ternary"           : "error",
	"no-useless-computed-key"       : ["error", {enforceForClassMembers: true}],
	"no-useless-rename"             : "error",
	"no-useless-return"             : "error",
	"no-var"                        : "error",
	"object-shorthand"              : "error",
	"one-var-declaration-per-line"  : "error",
	"operator-assignment"           : "error",
	"prefer-arrow-callback"         : ["error", {allowNamedFunctions: true}],
	"prefer-const"                  : ["error", {destructuring: "all"}],
	"prefer-destructuring"          : "off",
	"prefer-exponentiation-operator": "error",
	"prefer-numeric-literals"       : "off",
	"prefer-object-has-own"         : "off",
	"prefer-object-spread"          : "error",
	"prefer-template"               : "error",
	"quote-props"                   : ["error", "consistent-as-needed"],
	"sort-imports"                  : ["error", {
		ignoreCase           : true,
		ignoreDeclarationSort: true,
		allowSeparatedGroups : true,
	}],
	"sort-vars"     : ["error", {ignoreCase: true}],
	"spaced-comment": ["error", "always", {
		line : {markers: ["/"]},
		block: {balanced: true},
	}],
	"strict": ["error", "never"],
	"yoda"  : "error",
}

export default {
	...basic,
	...extended,
}

